
apiVersion: v1
kind: Service
metadata:
  name: dns-svc-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  loadBalancerIP: 172.17.255.10
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
