image:
  tag: v0.1.3


replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  port: 80
  targetPort: 8080
  type: NodePort
  #NodePort: 31236