apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-restore
  namespace: csi
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi