apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vault
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
        access_log /dev/stdout;

        server {
            listen 443 ssl;

            server_name nginx.example.ru;

            ssl_certificate         /vault/secrets/server.cert;
            ssl_certificate_key     /vault/secrets/server.key;

            location = /basic_status {
                stub_status;
            }
        }
    }