kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: vault
  labels:
    app: nginx-ssl
spec:
  type: LoadBalancer
  selector:
    app: nginx-ssl
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443