apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: init
          image: busybox:1.31.0
          command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
          volumeMounts:
            - mountPath: /app
              name: app
      containers:
        - name: web
          image: wbe7/webapp:1.5
          volumeMounts:
            - mountPath: /app
              name: app
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/index.html"
              port: 8000
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: 8000
      volumes:
        - name: app
          emptyDir: {}