apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    app: nginx
    release: monitoring
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics