apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8000
      targetPort: 8000
      name: stub
    - port: 9113
      targetPort: 9113
      name: metrics