apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: productcatalogservice-prod
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 120m
              memory: 128Mi
            limits:
              cpu: 220m
              memory: 256Mi